// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQM0cVYfKYMiFRiAzuGAqmm3JHQo9AD70',
    appId: '1:325955051094:web:b927163c546b5711d465f7',
    messagingSenderId: '325955051094',
    projectId: 'flutter-todo123321',
    authDomain: 'flutter-todo123321.firebaseapp.com',
    storageBucket: 'flutter-todo123321.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw7eqWcVp_sxOh-3_YQJ5YJZeoyd4t0-U',
    appId: '1:325955051094:android:611050a51f785ea2d465f7',
    messagingSenderId: '325955051094',
    projectId: 'flutter-todo123321',
    storageBucket: 'flutter-todo123321.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVZub6m1jYBCmPtJqpVMyqMOd4-WCvHXs',
    appId: '1:325955051094:ios:a3f5af2e738cd726d465f7',
    messagingSenderId: '325955051094',
    projectId: 'flutter-todo123321',
    storageBucket: 'flutter-todo123321.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );
}
